### ISSUE TITLE
GUI interface for metadata entry

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbn-conversion-tools#1]
**Features**
* Dynamically construct sections for general, subject, ecephys, ophys depending on input arguments
* mark and enforce required fields
* intelligently handle session_start_time
* save currently filled fields to a text file (file navigator to name and place file)
* load fields from file
* file navigator to select data to convert
* convert identified data and combine with supplied metadata
    * use SpikeInterface if it's a supported format
    * if not, raise `NotImplementedError`. We'll work through other data types
* pip installable

see https://github.com/ben-dichter-consulting/giocomo-lab-to-nwb/blob/master/giocomo-lab-to-nwb/interface_gui.py

though if you want to use Qt instead that would be fine

**Comment by bendichter** [comment]
@luiztauffer

**Comment by luiztauffer** [comment]
@bendichter I'd say this Issue is done.
We should start making specific requests now
